name: RxLeviathan Utils

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'packages/rx-leviathan-utils/**'

jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run RxLeviathan Utils Unit Tests
        run: |
          cd ./packages/rx-leviathan-utils
          npm install
          npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
