name: RxLeviathan Compiler

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  Code Quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run RxLeviathan Compiler Unit Tests
        run: |
          cd ./packages/rx-leviathan-compiler
          npm install
          npm run coverage

      - name: Coveralls Report
        uses: coverallsapp/github-action@master
        with:
          base-path: 'packages/rx-leviathan-compiler'
          path-to-lcov: './coverage/lcov.info'
          github-token: ${{ secrets.GITHUB_TOKEN }}
